### ISSUE TITLE
Willing to translate .docx to markdown

### ISSUE THREAD

**Issue by jazzyjackson** [openmainframeproject/cobol-programming-course#1]
Hi @jmertic I saw your message over on the hackernews thread. I'm interested in following the course and learning COBOL but as it is I feel perfectly qualified to open some word docs and transpose them into markdown, let me know I can help.

**Comment by DanielRosenwasser** [comment]
We wrote a script a few years back to extract `.docx` content from our spec to Markdown if that's at all helpful. It's custom tailored to some of our styles though.

https://github.com/microsoft/TypeScript/blob/eb105efdcd6db8a73f5b983bf329cb7a5eee55e1/scripts/word2md.ts

IIRC it expects Word on a host Windows machine and the document being converted can't be open at that moment.

**Comment by OliverMaerz** [comment]
Here it is: [https://github.com/openmainframeproject/cobol-programming-course/issues/3#issuecomment-612977812](https://github.com/openmainframeproject/cobol-programming-course/issues/3#issuecomment-612977812)

**Comment by martinkeen** [comment]
@jazzyjackson thank you. We have used a locked styles Word template to create the content. I tried running the Word chapters through pandoc but am not getting a clean conversion, so I think some manual transposing may be necessary. We'll have the Word source uploaded shortly, perhaps you could take a look? Thanks!

**Comment by jazzyjackson** [comment]
So it was a little difficult, I want to get your feedback if it would be helpful to continue -- or maybe the PDF in the repo is good enough.

Here's what I was able to pull out from saving the word doc as HTML and then converting different HTML elements to markdown equivalents: [/jazzyjackson/cobol-programming-course/]( https://github.com/jazzyjackson/cobol-programming-course/blob/master/COBOL%20Programming%20with%20VSCode.md)

Still have to add the Table of Contents links by hand, so I did that up to chapter 3...

Good part about converting it to github markdown is you get cobol syntax highlighting for free, for example in [this example](https://github.com/jazzyjackson/cobol-programming-course/blob/master/COBOL%20Programming%20with%20VSCode.md#732----------------order-and-naming-of-paragraphs), but cleaning up all the code blocks will take some work too.

What do you think, is it an improvement to have this document in markdown?

**Comment by martinkeen** [comment]
@jazzyjackson a huge THANKS for this! Overall this is looking in good shape already. Looks like almost everything came across with the exception of:

- Links in the TOC and each chapter intro (beyond Chapter 3, as you mentioned)
- Some of the code blocks need a bit of a tidy up
- Some of the numbered lists, particularly with the labs, not rendering correctly (some are fine).

Ultimately we'd like to replace the .DOCX entirely with this markdown version so the community can continue to edit and add content to do. Would you happen to have any more time to look at some of these issues above? Thanks again!

**Comment by jmertic** [comment]
Hey @jazzyjackson - would you be willing to do a pull request with your fork so the larger community can help integrate your work?

One other thought as I see what's been produced - would it make sense to split each chapter into a new markdown file? I'm thinking it could make management a bit easier. Let me know your thoughts @jazzyjackson @martinkeen @Sudharsana-Srinivasan @paulnewt

**Comment by DanielRosenwasser** [comment]
My suggestion (as an outsider) is that if you're not seeing any delays in markdown preview tools (e.g. VS Code) I would just keep it in one file. I think that'll honestly be easier both to author and read because it gives you things like easier file content search and link navigation that just works. As a reader on GitHub, that's a huge plus.

The only reason to split things apart would be if you decided to create a website with the content. Until that point, I think a single doc is easier.

**Comment by DStatWriter** [comment]
Great work @jazzyjackson i'm happy to help review / contribute if you need a 2nd pair of eyes on this? 

Dan

**Comment by DStatWriter** [comment]
> Hey @jazzyjackson - would you be willing to do a pull request with your fork so the larger community can help integrate your work?
> 
> One other thought as I see what's been produced - would it make sense to split each chapter into a new markdown file? I'm thinking it could make management a bit easier. Let me know your thoughts @jazzyjackson @martinkeen @Sudharsana-Srinivasan @paulnewt

I think this could help the collaberative effort as it would make dividing the work up a lot easier and guard aganst doubling up

Dan

**Comment by martinkeen** [comment]
Thanks all. We've completed the update of the book content into markdown format as a single file.

**Comment by sccosel** [comment]
@martinkeen Wow!  Great work!  Thank you!

**Comment by paulnewt** [comment]
so now - i need to get busy with revisions

**Comment by sccosel** [comment]
@paulnewt Thanks for all your work on this!  I'm sure I speak for many, that this (and your) effort is really appreciated!  Scott
