### ISSUE TITLE
Issues Running IBM Developer

### ISSUE THREAD

**Issue by pineconeman09** [openmainframeproject/cobol-programming-course#101]
Hello everyone!
I'm currently experiencing some issues installing and running IBM Developer on my Mac Book running Catalina. Anyone have similar issues? It appears that my machine meets all of the HW/SW pre-reqs. I've tried both various install methods: IBM IM, eclipse p2, and installing directly from Eclipse software.
Whenever I download and unzip the IM file, I see a folder entitled "aqua-3.1-im-1.9.1-macosx-x86_64" with various folders. If I try to open any of the application files in this folder, I either receive a message indicating the file is damaged or one saying that "developer can't be verified."
If downloaded using the Eclipse p2 method, it will unzip showing the IBM Developer application, but upon opening, it gave me a message saying "unable to locate companion shared library."
Lastly, I tried installing via Eclipse software and was again unsuccessful.
Any help would be greatly appreciated.
Thanks!

**Comment by paulnewt** [comment]
Please post request for assistance in OMP COBOL slack channel
