### ISSUE TITLE
the ACCTREC file?

### ISSUE THREAD

**Issue by xt0fer** [openmainframeproject/cobol-programming-course#102]
where is the ACCTREC file in the distribution? is it either of the ./Labs/data files? are they compressed or something?

**Comment by sccosel** [comment]
Please follow this roadmap.  Your question is directly answered in the .pdf class manual, as long as it is followed, STEP by STEP.  You first need mainframe credentials.  It's all explained here: https://github.com/openmainframeproject/cobol-programming-course/issues/53
