### ISSUE TITLE
Zowe Explorer connection to z/OS success but no Hello World

### ISSUE THREAD

**Issue by fcrote** [openmainframeproject/cobol-programming-course#106]
Hi There

I have successfully connected to the Mainframe and have received a directory listing but am not finding contents.

I can see a dir  named Z99998.CBL  but it appears empty.  When rolling over error message in VSCode it says: ... You may not use this protected dataset. 
![nofiles](https://user-images.githubusercontent.com/64555265/80820038-c59fd700-8b9b-11ea-9282-43df0b53b677.png)

**Comment by paulnewt** [comment]
you need to reference your assigned ID

**Comment by paulnewt** [comment]
Incorrect ID referred - Reference personal ID
