### ISSUE TITLE
Chapter link is broken

### ISSUE THREAD

**Issue by oleg-1login** [openmainframeproject/cobol-programming-course#11]
Looks like only **Labs** is relevant. There is no **Chapter** folder.

**Comment by sccosel** [comment]
Where is the relevant course material that puts all the "pieces" in context?

**Comment by Sudharsana-Srinivasan** [comment]
@oleg-1login The course will launch tomorrow, April 14th. Please check back here!

**Comment by Sudharsana-Srinivasan** [comment]
Our team has been working getting the content out as we have it ready. The course will launch and be available tomorrow!

**Comment by Sudharsana-Srinivasan** [comment]
The course content has been uploaded in word and pdf formats.

**Comment by johnpevans** [comment]
Thank you all for putting this together!

**Comment by bhowe** [comment]
> Thank you all for putting this together!

Yep Im really happy about the modern tooling that surprised me.

**Comment by jrmalone93** [comment]
"Chapters" link still gets 404 error
Where can i find the Word and PDF files?

**Comment by cwansart** [comment]
> "Chapters" link still gets 404 error
> Where can i find the Word and PDF files?

Directly on the root of the repo: https://github.com/openmainframeproject/cobol-programming-course

Click on it -> Download

**Comment by Sudharsana-Srinivasan** [comment]
The chapter and lab links have been fixed in readme.md
