### ISSUE TITLE
Bad imagens on .md/.pdf - linux and windows

### ISSUE THREAD

**Issue by brunorozendo** [openmainframeproject/cobol-programming-course#110]
OS:
  Arch linux 64x - gnome  firefox
  Windows Pro 64x - firefox 

In the `.pdf`  and `.md` ALL images  with `VS Code` with **`light`** theme is bad.
It is almost impossible to read,

You can see page 17  has a image with great quality, but page 21 has a bad one.

Page 17:
![cobol_page_17](https://user-images.githubusercontent.com/5125193/80936993-ad050c00-8da9-11ea-9203-95be9835da37.png)

Page 21
![cobol_page_21](https://user-images.githubusercontent.com/5125193/80937003-b42c1a00-8da9-11ea-8809-f941e66767a6.png)

**Comment by its-crypted** [comment]
where can I get the clear images? because the zip folder have the same images and they are compiled in LATEX.

**Comment by MikeBauerCA** [comment]
Resolved by #233 - will be available in next PDF release
