### ISSUE TITLE
IDz Host Emulator Connection

### ISSUE THREAD

**Issue by gowide00** [openmainframeproject/cobol-programming-course#117]
I can't connect to the Host Emulator (connection fails) so I'm unable to do the TSO/ISPF training.

**Comment by peraciodias** [comment]
> Não consigo conectar ao Emulador de Host (falha na conexão), portanto, não consigo fazer o treinamento TSO / ISPF.

Hi !
can you help me with a question about cobol?

**Comment by tanto259** [comment]
Hi @gowide00 , try port 623 for TN3270 connection

While @peraciodias, feel free to ask us here, or you may get a faster response over at the #cobol-programming-course channel on the [Open Mainframe Project Slack workspace](https://slack.openmainframeproject.org/).
