### ISSUE TITLE
What's Next?

### ISSUE THREAD

**Issue by gowide00** [openmainframeproject/cobol-programming-course#121]
I finished the cobol-programming-course.  I plan to still take more tutorials on the IDz environment.  But what happens next?

**Comment by Dlthomass** [comment]
I am learning 1. how to create diffrent data set via TSO and  JCL way 2. write own hello world program, then run successfully via TSO and JCL submit way. IDZ not for free forever though. Hope this helps.

**Comment by sccosel** [comment]
> I finished the cobol-programming-course. I plan to still take more tutorials on the IDz environment. But what happens next?

See the second FAQ, here:  https://github.com/openmainframeproject/cobol-programming-course/issues/53

**Comment by gowide00** [comment]
My email address debg234@yahoo.com is not registered for openmainframeproject.slack.com.  Can someone please register my email address for this site?  It won't let me login.
    On Monday, May 18, 2020, 12:01:21 AM EDT, sccosel <notifications@github.com> wrote:  
 
 



I finished the cobol-programming-course. I plan to still take more tutorials on the IDz environment. But what happens next?


See the second FAQ, here: #53

**Comment by paulnewt** [comment]
try https://join.slack.com/t/openmainframeproject/shared_invite/zt-dq0gxome-sPwD~yaqd3JE733Np48djw

**Comment by gowide00** [comment]
Paul, thank you so much.  The email from reskills should have this link rather than the link provided.I have been trying to create an account for the openmainframeproject.slack.com and couldn't for at least a month..      On Monday, May 18, 2020, 11:31:57 AM EDT, Paul Newton <notifications@github.com> wrote:  
 
 


try https://join.slack.com/t/openmainframeproject/shared_invite/zt-dq0gxome-sPwD~yaqd3JE733Np48djw

**Comment by Sudharsana-Srinivasan** [comment]
@gowide00 The registration email should point here : https://slack.openmainframeproject.org/
to be able to register for OMP Slack workspace. Once in the workspace you can join the cobol-programming-course slack channel.

Please let me know if this is not the link you get in your registration email. Thanks!
