### ISSUE TITLE
PDF Example 15 looks incorrect

### ISSUE THREAD

**Issue by Todesangst** [openmainframeproject/cobol-programming-course#122]
In the PDF guide, example 15, there is a COBOL statement "PERFORM UNTIL COUNTER = 10 WITH TEST AFTER" which gives error on compilation

```
   000034                    PERFORM UNTIL LASTREC = 'Y' WITH TEST AFTER                           25

 ==000034==> IGYPS2072-S "WITH" was invalid.  Skipped to the next verb, period or procedure-name
                         definition.
```

While  PERFORM WITH TEST AFTER UNTIL LASTREC = 'Y'   works OK, and matches the language reference format.

**Comment by sandeep-sparrow** [comment]
PERFORM 000-PARAGRAPH WITH TEST AFTER UNTIL LASTREC = 'Y', try this
