### ISSUE TITLE
Section 8.2.1 (coding rules & reference format) requires editing

### ISSUE THREAD

**Issue by tJ3l33s** [openmainframeproject/cobol-programming-course#126]
The discussion below **Figure 1** contains lines with the following text seemingly in the wrong place:
- \#\#\#\# Sequence Number Area (columns 1 - 6)
- \#\#\#\# Indicator Area (column 7)
- \#\#\#\# Area A (columns 8 - 11)
- \#\#\#\# Area B (columns 12 - 72)
- \#\#\#\# Identification Area (columns 73 - 80)

In each case, what is the significance of the four consecutive number signs (\#\#\#\#)?

**Comment by MikeBauerCA** [comment]
These should be headings. This is corrected by #114 and will be available in the next release of the PDF.
