### ISSUE TITLE
Section 8.3.2 (four divisions of COBOL) requires editing.

### ISSUE THREAD

**Issue by tJ3l33s** [openmainframeproject/cobol-programming-course#127]
Only IDENTIFICATION DIVISION and PROCEDURE DIVISION have section numbers — 8.3.2.1 and 8.3.2.2, respectively.  Section 8.3.2.1 has the following seemingly misplaced text:
- \#\#\#\# ENVIRONMENT DIVISION
- \#\#\#\# DATA DIVISION

**Comment by MikeBauerCA** [comment]
This has been resolved.
