### ISSUE TITLE
Course #1 : COBOL SORT statement

### ISSUE THREAD

**Issue by raven300** [openmainframeproject/cobol-programming-course#142]
We can include a Lab with the COBOL sort verb, the lesser known COBOL counterpart to the DFSORT utility. 

The INPUT PROCEDURE (for pre-processing of incoming records before the sort) and OUTPUT PROCEDURE (for post-processing of the sorted records) clauses can be used to make the sort a little more interesting.

**Comment by sccosel** [comment]
FYI, using an internal COBOL sort is not considered best practice in every commercial IT shop I've worked at (5 different shops).

**Comment by raven300** [comment]
True, thanks. I think COBOL sort is less efficient than DFSORT. If we have a small enough data set to sort and need some processing before/after sort, a COBOL sort can prove convenient as we can accomplish all of it in a single program.

**Comment by ravindrachechani** [comment]
It is recommended to use JCL SORT instead of COBOL SORT. COBOL SORT is slower and complex than JCL SORT.
