### ISSUE TITLE
Getting wrong credentials error message in zowe explorer.

### ISSUE THREAD

**Issue by f4him** [openmainframeproject/cobol-programming-course#157]
I have got the credentials in my mail and I have used them correctly in the zowe explorer plugin. No matter what, everytime I am getting 'Invalid Credentials. Please ensure the username and password for mytest are valid or this may lead to a lock-out.'.

**Comment by jellypuno** [comment]
@f4him Please join the [Open Mainframe Slack Channel](https://slack.openmainframeproject.org/). You will be supported there
