### ISSUE TITLE
I give up! Compile PDF is a waste of time!

### ISSUE THREAD

**Issue by ClassRepo** [openmainframeproject/cobol-programming-course#163]
After an hour and a half of trying to get the LaTex files to compile. I have decided it's just not worth the effort. There is no training worth this much hassle, just to get the lessons. It's senseless. I don't see it getter better; even if I could get the pdfs to compile.

Questions I'm left with:

1. how much electricity has been wasted by numerous people having to compile the pdfs, and download the supporting software?
2. Why not a format that's easily usable, and lightweight like HTML instead? Would that offend the open-source gods who demand fealty to the make-it-as-difficult-as-possible-so-we-feel-superior rule? Or is posting a LaTex file way more cool, and possibly impressive to the "open sores" crowd?
3. Why did I have to download THREE software packages I will NEVER use again, for THREE pdfs? Especially considering lightweight alternatives were easily available.
4. Why did the creator of this course not give one minute of thought to the user of this "course?" Was usability not even considered?
5. Why PDF? the idea of PDFs is to stop the end-user from  changing the info. That is NOT necessary here.

The difference between professionals and amateurs is simple. Amateurs are more worried about looking good/cool, and impressing people who really don't matter; Pros want to get things done. The same can be said about "open source" vs "professional" software.

**Comment by edack** [comment]
WOW, the .md file is readable in a browser. At least it is on Centos 6.10
w/Firefox, Ubuntu 14.04 w/Chrome, and Win 10 w/ Chrome and Edge.

Idle curiosity, why do you have to compile LaTex at all? Most/All distros 
have it already as a package. Just 'sudo apt/yum install texlive' and Bobs 
your uncle.

---
#include <std.disclaimer>;      | select * from users
Ed Ackerman                     |    where users.clue = 1;
edack@kengel.com                | 0 rows returned

**Comment by moueza** [comment]
Hi,
ClassRepo is right. It is just a hassle just to compile into pdf in linux :

In commit,a8d4e38, 
`pandoc "COBOL Programming Course #1 - Getting Started.md" -o "COBOL Programming Course #1 - Getting Started.pdf" --number-sections --toc -B Front_Matter.tex --listings`
gives
```

! LaTeX Error: Undefined color `black!10'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.984 \begin{lstlisting}

pandoc: Error producing PDF
```
+ code4z-img5.PNG is misspelled

So it has not been compiled before submission into master !

Why don't you just deliver the pdf ?

It is very discouraging to go further with COBOL !

**Comment by moueza** [comment]
` .md file is readable in a browser` : the comfort is really not the same, because the browser does not translate .md into html

**Comment by moueza** [comment]
`why do you have to compile LaTex at all` : because it is the [recommended way](https://github.com/openmainframeproject/cobol-programming-course/tree/master/COBOL%20Programming%20Course%20%231%20-%20Getting%20Started#build)

**Comment by moueza** [comment]
Tried a fixing Pull Request but forbidden

Here is the pdf 

[COBOL Programming Course #1 - Getting Started.pdf](https://github.com/openmainframeproject/cobol-programming-course/files/4909914/COBOL.Programming.Course.1.-.Getting.Started.pdf)

**Comment by jellypuno** [comment]
> Tried a fixing Pull Request but forbidden

Really? What is the error that you are experiencing? Others were able to open a PR.

**Comment by moueza** [comment]
My branch not allowed to open for the PR
` git push
fatal: The current branch moueza-compiling-course-1-into-pdf has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin moueza-compiling-course-1-into-pdf

peter@oscillan1:~/POUB/cobol-programming-course/COBOL Programming Course #1 - Getting Started$  git push --set-upstream origin moueza-compiling-course-1-into-pdf
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
ERROR: Permission to openmainframeproject/cobol-programming-course.git denied to moueza.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by MikeBauerCA** [comment]
@moueza @ClassRepo you can build the PDF but you absolutely do not need to. All releases of the course are published at https://github.com/openmainframeproject/cobol-programming-course/releases. 

If you would like to contribute, feel free to just contribute to the markdown files. I create the official releases from the markdown files and will find/correct any PDF generation issues during PR review or the release creation process. The PDF is gitignored and not sourced in the repo. Git handles merge conflicts between markdown files much better than PDFs which significantly reduces the maintenance of this repo.

**Comment by moueza** [comment]
OK thank you @MikeBauerCA for pdf links +++++ , advice. And indeed, .md files are more convenient for version control.

**Comment by moueza** [comment]
Hi @jellypuno , I will try an other time...
