### ISSUE TITLE
syntax highlighting not working because files don't have an extension

### ISSUE THREAD

**Issue by JosefKaser** [openmainframeproject/cobol-programming-course#18]
The COBOL files in the "cbl" folder don't have any of the known file extensions mentioned in chapter 2.2.1 of the "COBOL Programming with VS Code" PDF. Thus syntax highlighting in the Z Open Editor does not work as described.

**Comment by Sudharsana-Srinivasan** [comment]
Thank you @JosefKaser for bringing this up. Looking into it now

**Comment by Sudharsana-Srinivasan** [comment]
The COBOL file extension can be renamed to .COBOL. Hope that helps

**Comment by oleg-1login** [comment]
Is there a reason not to update the master branch with .COBOL extensions?

**Comment by cwansart** [comment]
I am not 100 % sure but I think file extensions are unusable on systems like z/OS. Those files were probably copied from there without any extension.

You can enable the syntax highlighting when clicking on the bottom right corner on the current syntax highlighting. I guess it is "text only" or something like that. See: https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file

**Comment by JosefKaser** [comment]
> The COBOL file extension can be renamed to .COBOL. Hope that helps

Thank you @Sudharsana-Srinivasan for this tip which was also my solution. But as the course is designed to be carried out in the Z Open Editor I thought it would be a good idea to add the extensions to the files in the repository because others may also come across this issue.

**Comment by jazzyjackson** [comment]
Another way to handle this automatically is to add the path `"**/cbl/**"` to the file associations setting in VS Code's settings.json. I clicked View -> Command Palette (Ctrl Shift P) and typed "Open Settings JSON" and Enter, here's what mine looks like after editing, and all the files in the Labs/cbl directory are highlighted for me now.

```json
{
   "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
   "git.autofetch": true,
   "window.zoomLevel": 1,
   "files.associations": {
        "*.COBOL*": "cobol",
        "*.COB*": "cobol",
        "*.COBCOPY*": "cobol",
        "*.COPYBOOK*": "cobol",
        "*.COPY*": "cobol",
        "*.PL1*": "pl1",
        "*.PLI*": "pl1",
        "*.INC*": "pl1",
        "*.INCLUDE*": "pl1",
        "*.JCL*": "jcl",
        "**/cbl/**": "cobol"
    },
    "zopeneditor.JAVA_HOME": "C:\\Program Files\\OpenJDK\\jdk-14"
}
```

**Comment by kas1830** [comment]
It's also worth to mention you also need to put here actual path to your Java reference:
"zopeneditor.JAVA_HOME": "C:\\Program Files (x86)\\Java\\jre1.8.0_31"
