### ISSUE TITLE
Chapters link is 404 on Readme.md

### ISSUE THREAD

**Issue by bolaurent** [openmainframeproject/cobol-programming-course#19]
This link is 404

![image](https://user-images.githubusercontent.com/1839790/79276531-0e962280-7e5d-11ea-9340-849c5ec88418.png)

**Comment by camdroid** [comment]
I think this is a duplicate of #11.

**Comment by Sudharsana-Srinivasan** [comment]
Will update the link to point to the Course pdf

**Comment by martinkeen** [comment]
Thank you. Fixed.
