### ISSUE TITLE
Simplified (non-Zowe) solution to Adv Challenge 3.2

### ISSUE THREAD

**Issue by johnmacinnis** [openmainframeproject/cobol-programming-course#195]
In case anyone is interested:

My code here: https://github.com/johnmacinnis/openmainframeChallenge3.2_simplified_answer

Simple solution to OpenMainframe Adv Challenge3.2 using only ISPF and Mainframe COBOL (non-Zowe solution) The details of this project can be found at https://github.com/openmainframeproject/cobol-programming-course A most elegant solution using Typescript to automate json to csv conversion + the Zowe API Visual Studio plugin to access the IBM sponsored mainframe - by the code master/challenger here https://medium.com/@jessielaine.punongbayan/solution-covid-19-reports-cobol-challenge-6c509579e3fe

If like me, you are renting $50/mo access from a commercial mainframe provider, the Zowe interface is generally not available. No problem. Here I show a simple solution to this challenge using only ISPF and COBOL from a standard mainframe access provider.

**Comment by MikeBauerCA** [comment]
Thanks for sharing your solution. Closing as no further action is required.
