### ISSUE TITLE
pdf1 no 103

### ISSUE THREAD

**Issue by moueza** [openmainframeproject/cobol-programming-course#197]
I am reading pdf1, 10.4 Lab
`4. Submit job, JCL(CBL0001J), within the DATA SET section.

5. View that job output using the JOBS section.

• COBRUN:SYSPRINT(101) - COBOL program compiler output

• RUN:PRTLINE(103) - COBOL program execution output, `

5. They speak about 103 output

I've tried on the machine, I've just 101 and 102 but no 103.

Can you try and confirm please ?

**Comment by tanto259** [comment]
You should be able to see 101, 102, 103. 

If you still can't see it, can you post some screenshot over at the #cobol-programming-course channel on the [Open Mainframe Project Slack](https://slack.openmainframeproject.org/)?

We can help you faster there :)
