### ISSUE TITLE
Improve debugging article

### ISSUE THREAD

**Issue by OlegKunitsyn** [openmainframeproject/cobol-programming-course#199]
The course explains usage of 'D' without working example. Programming Guide Version 6.2 and googling did not help.
hello.cbl:
```
       IDENTIFICATION DIVISION.
       PROGRAM-ID. HELLO.
       PROCEDURE DIVISION.
           DISPLAY 'Hello'.
      D    DISPLAY 'World'.
           STOP RUN.
       END PROGRAM HELLO.
```
hello.jcl:
```
//HELLO JOB 1,NOTIFY=&SYSUID
//COMPILE      EXEC IGYWCL,PARM='TEST'
//CEEOPTS      DD * DEBUG
//COBOL.SYSIN  DD DSN=&SYSUID..CBL(HELLO),DISP=SHR
//LKED.SYSLMOD DD DSN=&SYSUID..LOAD(HELLO),DISP=SHR
// IF RC = 0 THEN
//RUN          EXEC PGM=HELLO,PARM='TEST'
//CEEOPTS      DD * DEBUG
//STEPLIB      DD DSN=&SYSUID..LOAD,DISP=SHR
//PRTLINE      DD SYSOUT=*
//SYSOUT       DD SYSOUT=*
//SYSDEBUG     DD SYSOUT=*
//CEEDUMP      DD SYSOUT=*
//SYSUDUMP     DD SYSOUT=*
// ELSE
// ENDIF
```
displays `Hello` only. 
Which `PARM` or/and `CEEOPTS` will compile debug lines?

**Comment by OlegKunitsyn** [comment]
@jellypuno can you help please?

**Comment by jellypuno** [comment]
@OlegKunitsyn Add WITH DEBUGGING MODE in SOURCE-COMPUTER.

https://www.ibm.com/support/knowledgecenter/SSQ2R2_9.1.1/com.ibm.ent.cbl.zos.doc/PGandLR/ref/rlconsou.html

**Comment by OlegKunitsyn** [comment]
Yes, I'm aware of the solution on COBOL-level which enables debugging in particular program. Is there a way to enable debugging mode compiling all sub-programs and included libraries without changing all the source-code?

**Comment by jellypuno** [comment]
@OlegKunitsyn I'm not sure. Maybe @paulnewt knows. 

All I know is that the 'D' can serve as a comment/debug point. If I really need to debug my program, I use a different tool (e,g. Intertest)

**Comment by OlegKunitsyn** [comment]
Seems there is no JCL flags for that. Thank you for an idea!
