### ISSUE TITLE
Help me get Visual Studio/Open Editor setup

### ISSUE THREAD

**Issue by tathoma** [openmainframeproject/cobol-programming-course#20]
It's been 20 years since I've worked with Visual studio.  I downloaded and installed the Community version.  I didn't know what packages to pick so I randomly picked a component so it would finish the install.  In the extension marketplace, I can't find the IBM Z Open Editor extension.  When I visit via the web I can find it, but when I clicked Install it told me I didn't have Visual Studio setup.  Do I need to have a paid version of VS or something?

**Comment by Sudharsana-Srinivasan** [comment]
Hope you are following instructions in Chapter 3

**Comment by bhowe** [comment]
Uses visual studio code I think which is the free version.

**Comment by tathoma** [comment]
Haha, that was it. I didn't realize Visual Studio Code was a separate application.  I just thought they were referring to code in Visual Studio.  Thanks.
