### ISSUE TITLE
Lab 2 error

### ISSUE THREAD

**Issue by al-heisner** [openmainframeproject/cobol-programming-course#21]
There's no error in Lab 2's PAYROLL0X source. I did a diff on the two source files looking to see what changed, nothing in reference to GROSS-PAY was changed in the source file that was supposed to produce compile error.

**Comment by Sudharsana-Srinivasan** [comment]
We are working on this... thank you for capturing it here

**Comment by kas1830** [comment]
> There's no error in Lab 2's PAYROLL0X source. I did a diff on the two source files looking to see what changed, nothing in reference to GROSS-PAY was changed in the source file that was supposed to produce compile error.

check PIC 9(5) vs PIC X(5)

**Comment by al-heisner** [comment]
I'm sure that was the intention, but neither source file in the github
repository has PIC X(5). Both contain PIC 9(5).

**Comment by paulnewt** [comment]
lab corrected

**Comment by diocles** [comment]
@paulnewt I've just run into this issue, having uploaded the files myself from git - is it possible you have fixed this on the lab mainframe, but not in this source repository?
