### ISSUE TITLE
Descargar Enterprise COBOL v6.3 

### ISSUE THREAD

**Issue by sirwilliam35** [openmainframeproject/cobol-programming-course#220]
Cordial saludo.
Mi solicitud es para saber donde puedo descargar Enterprise COBOL v6.3 para hacer estas prácticas.

**Comment by tanto259** [comment]
There's a Spanish translation of the course available here: https://github.com/openmainframeproject/cobol-programming-course/files/5853173/1.-.Configurando.VSCode.pdf

But to quote the translation,

> **Proveedores** 
Estos materiales están siendo utilizados por otras organizaciones para brindar capacitación 
sobre COBOL a la comunidad. Ni este proyecto ni Open Mainframe Project revisan, mantienen 
ni respaldan a ninguno de estos proveedores en particular. Si está utilizando estos documentos 
en sus materiales de capacitación, no dude en editarlos y emitir una solicitud de extracción 
para incluirlos. 
> -[ IBM ha proporcionado un entorno gratuito para completar este laboratorio. ](https://www-40.ibm.com/events/wwe/ast/mtm/cobolvscode.nsf/enrollall?openform)

That will give you access to a z/OS environment with Enterprise COBOL v6.3 available.

For further assistance, do check out the #cobol-programming-course channel on the [Open Mainframe Project Slack workspace](https://slack.openmainframeproject.org).
