### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by wawesomeNOGUI** [openmainframeproject/cobol-programming-course#226]
Hi! I’m excited to start taking this course, and I found the pdfs under the latest release, but the main link: https://www.openmainframeproject.org/projects/coboltrainingcourse has a 404 error

**Comment by tanto259** [comment]
Try https://www.openmainframeproject.org/projects/cobolprogrammingcourse :)

**Comment by wawesomeNOGUI** [comment]
Oh nice that link worked thanks! So is the recommended way to follow the course to download the pdfs?

**Comment by tanto259** [comment]
The PDFs are the latest release of the course. If you prefer videos, there are some video courses linked on the README :)

**Comment by wawesomeNOGUI** [comment]
Oh awesome thanks!

**Comment by wawesomeNOGUI** [comment]
Should we change the website link in the about section somehow?

**Comment by tanto259** [comment]
> Should we change the website link in the about section somehow?

Now the old link will redirect to the new one :)

**Comment by wawesomeNOGUI** [comment]
Oh awesome! Thanks :)
