### ISSUE TITLE
VSCode with OpenJDK on Linux Ubuntu

### ISSUE THREAD

**Issue by varlux** [openmainframeproject/cobol-programming-course#26]
Syntax highlighting don't work on my PC....it seems because something (....maybe OpenJDK?) is not set correctly.

VSCode says:"The Java Runtime path is not correctly configured for the IBM"

Environment variable JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/bin/java

What can I do?

**Comment by kas1830** [comment]
Try using native IBM Java 8 instead: https://developer.ibm.com/javasdk/downloads/eclipse/

**Comment by varlux** [comment]
ok .... I'm afraid of making a mistake. Could you tell me which file to download? Do I have to uninstall OpenJDK first? Thank you

**Comment by java007md** [comment]
I added:

`JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64`

inside /etc/environment, and ran:

`source /etc/environment`

vscode seems to be working for me with IBM Z Open Editor extension installed. Not knowing COBOL, I'm not positive though.

**Comment by varlux** [comment]
> I added:
> 
> `JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64`
> 
> inside /etc/environment, and ran:
> 
> `source /etc/environment`
> 
> vscode seems to be working for me with IBM Z Open Editor extension installed. Not knowing COBOL, I'm not positive though.

I followed your instructions, but I always get the same error

**Comment by kas1830** [comment]
> ok .... I'm afraid of making a mistake. Could you tell me which file to download? Do I have to uninstall OpenJDK first? Thank you

I've picked **IBM_DevelopmentPackage_for_Eclipse_Win_X86_64_6.6.5.zip** and put the unzipped folder on C:\COBOL\...
Works fine to me 👍

**Comment by varlux** [comment]
> > ok .... I'm afraid of making a mistake. Could you tell me which file to download? Do I have to uninstall OpenJDK first? Thank you
> 
> I've picked **IBM_DevelopmentPackage_for_Eclipse_Win_X86_64_6.6.5.zip** and put the unzipped folder **ibm_sdk80** to C:\COBOL...
> Works fine to me

.....I'm working on a Linux machine.....

**Comment by varlux** [comment]
OK Boys, I set the correct path in the settings.json configuration file and it works.

`"zopeneditor.JAVA_HOME": "/usr/lib/jvm/java-11-openjdk-amd64"`

Thank you all
