### ISSUE TITLE
Update course with survey result from COBOL WG

### ISSUE THREAD

**Issue by tanto259** [openmainframeproject/cobol-programming-course#263]
### Course Details

GitHub

### Description

The first chapter of Course 2 highlights [several facts on the use of COBOL on today's era](https://github.com/openmainframeproject/cobol-programming-course/blob/master/COBOL%20Programming%20Course%20%232%20-%20Learning%20COBOL/COBOL%20Programming%20Course%20%232%20-%20Learning%20COBOL.md#how-is-cobol-being-used-today). 

With the recent survey conducted by the COBOL Working Group, we may want to take a look at the result of the survey, and incorporate that to the chapter or replace the existing content with updated and cited data from the survey.

### Additional Context

**Links:**
- Survey results are available on this TechChannel article: https://techchannel.com/Trends/10/2021/special-report-cobol-survey
- COBOL Working Group mailing list: https://lists.openmainframeproject.org/g/wg-cobol

**Currently listed statements:**
> COBOL is everywhere. You have probably used an application written in COBOL today. For example, consider the following statistics:
> - About 95% of ATM swipes use COBOL code.
> - COBOL powers 80% of in-person transactions.
> - Every day, COBOL systems handle $3 trillion in commerce.
>
> How pervasive is COBOL? Consider these mind-boggling facts:
> - Every day there are 200 times more COBOL transactions executed than there are Google searches.
> - There are over 220 billion lines of COBOL programs running today, which equates to around 80% of the world's actively used code.
> - 1,500,000,000 lines of new COBOL code are written each year.

**Comment by Sinthie** [comment]
😍

**Comment by tanto259** [comment]
Hi @ashiskumarnaik, thanks for your interest in contributing back to the course. On release 3.0.0 of the course, we split Course 1 into two, thus the referred chapter is now relocated to Course 2. Main post updated to reflect that. Thank you!

**Comment by ashiskumarnaik** [comment]
HI @tanto259 , yeah I got that and the PR is updated as you said :)
