### ISSUE TITLE
Unable to join Slack workspace.

### ISSUE THREAD

**Issue by DirtySoc** [openmainframeproject/cobol-programming-course#273]
### Course Details

GitHub

### Description

Unable to login to the slack workspace at https://openmainframeproject.slack.com/

When trying to create an account I do not have an email from one of the required domains: 

<img width="732" alt="image" src="https://user-images.githubusercontent.com/33207400/191283581-68733b7c-5879-4de7-800b-7c8d8bc6b095.png">

### Reproduction Steps

1. Sign up for course at https://www-40.ibm.com/events/wwe/ast/mtm/cobolvscode.nsf/enrollall?openform
2. Receive email from IBM with instructions to set first time mainframe password with the Slack bot.
3. Go to https://openmainframeproject.slack.com/ to sign in / create an account on the workspace.

**Comment by tanto259** [comment]
Hi @DirtySoc,

Seems that the invite link is broken. I'll see if I can reach out to someone to get it fixed.

In the meanwhile, this should work: https://join.slack.com/t/openmainframeproject/shared_invite/zt-1gkhwtzsx-EZuJXgu05N67AWyalJJq_A

Thank you!

**Comment by DirtySoc** [comment]
Thanks for the link. That works for me!
