### ISSUE TITLE
Error in binary-ranges-3.png (Length and Range at S9(9) is wrong

### ISSUE THREAD

**Issue by vargajb** [openmainframeproject/cobol-programming-course#282]
### Course Details

GitHub

### Description

The variables marked in blue are not 8 bytes long, but only 4 bytes long. See attached compiler list (on the picture).
Accordingly, "Range" is also incorrect.
Two unnecessary commas are marked in red.
The attached picture shows the error in detail.

![binary-ranges-3](https://user-images.githubusercontent.com/113785741/197869537-c54902ec-ec36-44e6-ab06-04d8f5249452.png)

### Reproduction Steps

1.
2.
3.
...

**Comment by vargajb** [comment]
@tanto259 I cannot correct this error personally, because I do not have the original Excel table from which the image was generated.

**Comment by tanto259** [comment]
I'll see if I can trace back the Excel sheet, and also the individual who submitted the PR. But it seems that worst case, we will need to either edit the image or re-create the sheet...
