### ISSUE TITLE
No Labs or samples provided

### ISSUE THREAD

**Issue by multijoy** [openmainframeproject/cobol-programming-course#295]
### Course Details

GitHub

### Description

The PDFs reference source files (CBL0001, etc) which appear to exist in #2, but no reference is made in #1.
...

**Comment by tanto259** [comment]
Hi, we recently re-arranged the course with release 3.0.0. As a result of the arrangement, the old Course 1 is split into 2 different courses: Course 1 (Getting Started) and Course 2 (Learning COBOL).

Course 1 details all the background information regarding the toolings that the course utilized, while Course 2 is the actual course content. The Labs are available on the Course 2 folder: https://github.com/openmainframeproject/cobol-programming-course/tree/master/COBOL%20Programming%20Course%20%232%20-%20Learning%20COBOL
