### ISSUE TITLE
Unable to join Slack - Account deactivated

### ISSUE THREAD

**Issue by stefanrusso** [openmainframeproject/cobol-programming-course#296]
### Course Details

GitHub

### Description

Years ago I started the Cobol course, but I was sidetracked by real life.  When I try to join the Slack workspace, I get the error below.  I could not find any other place to contact a workspace administrator to remedy the issue.

![image](https://user-images.githubusercontent.com/1565266/225998641-cdd82891-dff4-4719-b4a7-cfe5ae404033.png)

### Reproduction Steps

1. Click on the Slack link in the course's main GitHub page.
2. Sign-in to Slack
3. Receive above email.
...

**Comment by tanto259** [comment]
Hi Stefan,

I have reached out to the administrators of the Slack workspace, and I was informed that they have reactivated your account.

If you are still having issue, feel free to re-open this issue. Thank you!
