### ISSUE TITLE
A Word document as readme in a github repo?

### ISSUE THREAD

**Issue by OliverMaerz** [openmainframeproject/cobol-programming-course#3]
Labs/$README.docx :-1:

**Comment by kas1830** [comment]
OK, next steps?

**Comment by michael-conrad** [comment]
Pandoc convert it to gfm flavored markdown?

**Comment by OliverMaerz** [comment]
COBOL labs
4 folders

1. **cbl** – COBOL source code
2. **jcl** – JCL to compile, link, and execute COBOL source code
3. **jclproc** – JCL PROCEDUREs used for labs in JCL folder
4. **data** – COBOL program input records

Note:
**cbl** folder
- copy cobol source members into student id.CBL partitioned data set name

**jcl** folder 
- copy jcl members into student id.JCL partitioned data set name
- jcl members reference student id.CBL and student id.LOAD partitioned data set names

**jclproc** folder 
- members need to be copied into z/OS JES procedure library

**data** folder
- member **data** must be transferred binary to z/OS because the data contains EBCDIC and Packed Decimal
- member **datax** is a viewable ASCII data but the packed decimal fields were translated to ASCII and are unreadable
`

**Comment by OliverMaerz** [comment]
```
COBOL lCOBOL labs
4 folders

1. **cbl** – COBOL source code
2. **jcl** – JCL to compile, link, and execute COBOL source code
3. **jclproc** – JCL PROCEDUREs used for labs in JCL folder
4. **data** – COBOL program input records

Note:
**cbl** folder
- copy cobol source members into student id.CBL partitioned data set name

**jcl** folder 
- copy jcl members into student id.JCL partitioned data set name
- jcl members reference student id.CBL and student id.LOAD partitioned data set names

**jclproc** folder 
- members need to be copied into z/OS JES procedure library

**data** folder
- member **data** must be transferred binary to z/OS because the data contains EBCDIC and Packed Decimal
- member **datax** is a viewable ASCII data but the packed decimal fields were translated to ASCII and are unreadable
`abs
4 folders

1. **cbl** – COBOL source code
2. **jcl** – JCL to compile, link, and execute COBOL source code
3. **jclproc** – JCL PROCEDUREs used for labs in JCL folder
4. **data** – COBOL program input records

Note:
**cbl** folder
- copy cobol source members into student id.CBL partitioned data set name

**jcl** folder 
- copy jcl members into student id.JCL partitioned data set name
- jcl members reference student id.CBL and student id.LOAD partitioned data set names

**jclproc** folder 
- members need to be copied into z/OS JES procedure library

**data** folder
- member **data** must be transferred binary to z/OS because the data contains EBCDIC and Packed Decimal
- member **datax** is a viewable ASCII data but the packed decimal fields were translated to ASCII and are unreadable
```

**Comment by OliverMaerz** [comment]
Pull request https://github.com/openmainframeproject/cobol-programming-course/pull/6

**Comment by sccosel** [comment]
Where is the Coursera Cobol course?  That is, how do we sign up for the actual IBM Cobol course?
Thanks,Scott
    On Monday, April 13, 2020, 10:14:09 AM PDT, Oliver Maerz <notifications@github.com> wrote:  
 
 


Pull request #6

**Comment by paulnewt** [comment]
many of the points here are addressed....
