### ISSUE TITLE
Enhancement: Include Open Source Zowe CLI in the Course

### ISSUE THREAD

**Issue by MikeBauerCA** [openmainframeproject/cobol-programming-course#31]
Awesome initiative, I hope to be able to contribute to this project :)

Command line interfaces can significantly improve development processes through the use of scripting. Zowe CLI is an open source tool that provides remote interaction with the mainframe and as an extensible technology, mainframe development products.

The Zowe CLI enables developers and DevOps engineers to control, script and develop on the mainframe like any other cloud platform and allows them to make use of familiar, industry-standard, open-source tooling. This helps address the skills gap and onboard COBOL developers by making mainframe development more attractive and accessible.

I intend to open a PR that adds a chapter introducing Zowe CLI, Zowe CLI Plug-ins, and how these technologies can help folks working with mainframe COBOL apps. It will also add a chapter on the installation of Zowe CLI and Plug-ins. 

In a future issue/PR, I also intend to add a lab for using the command line interface and developing automation that will follow a similar structure to the first lab using the Zowe Explorer.

**Comment by Sudharsana-Srinivasan** [comment]
Thank you. Look forward to it!

**Comment by jacqpot** [comment]
that would be so helpful! I spent a few hours trying to get the zowe CLI content to work after noticing that the lecture content uses it without showing me how!! Thanks again.

**Comment by timdsaunders1** [comment]
This is great, looking forward to seeing this valuable contribution to enable developers & DevOps engineers to control, script and develop on the mainframe, like any other cloud platform.
