### ISSUE TITLE
Help with the basics

### ISSUE THREAD

**Issue by jacqpot** [openmainframeproject/cobol-programming-course#32]
Thanks for the cobol course. I cant help but notice that this course is not being presented for new people trying to learn to program in cobol.  But for people with a wide range of programming knowledge albiet not cobol.

So I've got a few questions I hope you can help with. 

- How do I link the actual files (which don't have an extension) on my laptop with the JCL and via that to the file referenced in the select statement. 
- Although I have a zowe profile setup and Java correctly designated I still do not have the functionality of the zowe extension for the cobol programs (floating information block when hovering over code). 
- Breadcrumb function does not work
-when trying to run a program I get this message back. "cannot find a class with the main method in the folder 'cobol resources'"

which leads me to figuring out what this is--- "Check at least one main class exists in your workspace." -when referencing the help content

Thanks so much for your help on this. 

please respond here or email me at potgieter.g.jacques@gmail.com if you can help out!

**Comment by jacqpot** [comment]
I noticed that I have not done any of the Readme file orders. I actually have no idea how to do those things.
 IE: copy cobol source members into student id.CBL partitioned data set name

1. what are source members
2. what/where are the partitioned data set name.

so on and so forth for .cobol jcl and jclproc files.

Again thank you so much for helping someone so new to programming.

**Comment by paulnewt** [comment]
https://www.eventbrite.com/e/a-beginners-practical-approach-to-cobol-tickets-102714511870 listen for announcement of access to z/OS for the COBOL labs - no cost   where labs data sets (COBOL source, JCL, data is provided on the lab system for each participant that enrolls

**Comment by jacqpot** [comment]
Thanks Paul.

**Comment by kas1830** [comment]
> Although I have a zowe profile setup and Java correctly designated I still do not have the functionality of the zowe extension for the cobol programs (floating information block when hovering over code).
Breadcrumb function does not work
-when trying to run a program I get this message back. "cannot find a class with the main method in the folder 'cobol resources'"

The same happened to me. Using original IBM Java 8 fixed that 👍
