### ISSUE TITLE
about the installation of vs code 

### ISSUE THREAD

**Issue by Dlthomass** [openmainframeproject/cobol-programming-course#34]
I have installed them, just wondering
1. Does they have compiler in there like Open Cobol IDE?
2. Who can show me a video, how to use vs code to edit and debug Cobol?

Appreciated.
Tom

**Comment by Dlthomass** [comment]
Who has run the "Hello world" successfully?

**Comment by negovan13** [comment]
I didn't. As I wrote earlier, I am stuck on chapter 4.6, same as many of us beginners.

**Comment by EddieCavic** [comment]
Hello negovan13
What is your issue?
I have run Hello pgm successfully.
I can help you
Eddie
