### ISSUE TITLE
IP address and port number for COBOL Programming with VSCode Labs Confirmation

### ISSUE THREAD

**Issue by negovan13** [openmainframeproject/cobol-programming-course#35]
What is IP address for connecting to z/OS? I successfully registered for COBOL Programming with VSCode Labs Confirmation, just need IP and port :)

**Comment by Sudharsana-Srinivasan** [comment]
IP address for VSCode extension: https://192.86.32.250:10443
IP address for TN3270: 192.86.32.250 Port 623
IP address for IDz: 192.86.32.250 Port 4035

**Comment by sccosel** [comment]
Are there instructions to connect the IDE with other customer owned/leased z/OS systems?

**Comment by fromer97** [comment]
What is the usr name and password for the VSCode extension?

**Comment by EddieCavic** [comment]
Hello fromer97
You can request from README, Providers section.
It is necessary to request a new user, after that you receive an email confirming and providing user/psw.

**Comment by EddieCavic** [comment]
> What is the usr name and password for the VSCode extension?

Hello
You can request from README, Providers section.
It is necessary to request a new user, after that you receive an email confirming and providing user/psw.

**Comment by fromer97** [comment]
Got it....thanks, did not see that link a couple days ago.

**Comment by Sudharsana-Srinivasan** [comment]
This information is part of your system registration confirmation email
