### ISSUE TITLE
Cannot join Slack

### ISSUE THREAD

**Issue by broarr** [openmainframeproject/cobol-programming-course#37]
Hi all, 

I'm probably missing something simple, but I can't access the slack channel for the cobol course that's listed in the email sent to people looking for a COBOL environment to run code in. I'm talking about this link:

![image](https://user-images.githubusercontent.com/49485134/79595383-b9505000-80ac-11ea-99d2-7ba5f1188cd3.png)

That leads to:

https://openmainframeproject.slack.com/

Any help would be greatly appreciated!

**Comment by sccosel** [comment]
Same issue.  @broarr you are not alone!

**Comment by moonman7** [comment]
In the class webinar the slide says 
https://slack.openmainframeproject.org
 Notice   slack  is first
I have not tried it yet.

**Comment by broarr** [comment]
Thanks @moonman7! Working for me too!
