### ISSUE TITLE
Access to Slack workspace

### ISSUE THREAD

**Issue by bkline** [openmainframeproject/cobol-programming-course#40]
Catch 22. From the registration email message:

> We are using Slack for system access questions and password issues:
Click this link to add yourself to the Open Mainframe Project Slack workspace. Within this workspace, add the cobol-programming-course channel.

But that link takes you here. What do you do if you don't have an email address at any of the four domains named in the "If you have ... you can create an account" instructions?

![image](https://user-images.githubusercontent.com/1634628/79637353-db99aa80-814c-11ea-9dc2-df0aec50858d.png)

**Comment by streffurth** [comment]
At this link you have to enter your email and than you can sin up for the slack https://slack.openmainframeproject.org/

**Comment by bkline** [comment]
Thanks. Unfortunate that the link in the registration email message doesn't take you to that page. :
