### ISSUE TITLE
PICTURE Clause documentation appears to be incorrect.

### ISSUE THREAD

**Issue by abickerton** [openmainframeproject/cobol-programming-course#41]
> 5.2.3
> PICTURE clause character-string representation
> Some PIC clause symbols can appear only once in a PIC clause character-string,
> while other can appear more than once. For example:
> ➢ PIC clause to hold value 1123.45 is coded as follows, where the V represents
> the decimal position.
> PIC 9(4)V99
> ➢ PIC clause for a value such as $1,123.45 is coded as follows:
> PIC $9,999V99

When this is applied to the PAYROL00.CBL (Lab 2) the following is observed.
e.g.
...
77  GROSS-PAY  PIC $9(4)V99.
....
Expected :  Gross Pay: $0437.00
Actual :  Gross Pay: $043700

Is the documentation wrong? or am I missing something obvious.

**Comment by sccosel** [comment]
They haven’t yet discussed displaying numbers which are not whole numbers!  If you want to make this work, try defining another variable called:
77 GROSS-PAY-DISPLAY PIC $$$$9.99.
And add these 2 statements after the COMPUTE of GROSS-PAY:
MOVE GROSS-PAY TO GROSS-PAY-DISPLAY
DISPLAY ‘Gross Pay Formatted: ‘ GROSS-PAY-DISPLAY.

Let us know how that goes!
ScottC

**Comment by sccosel** [comment]
@abickerton Did you try the suggestion?  How did it go?

**Comment by abickerton** [comment]
@sccosel 

Yes that works. But that doesn't answer the question why the docs state the following.
> PIC clause for a value such as $1,123.45 is coded as follows: PIC $9,999V99

Yet when it's used, the value shown is wrong (Gross Pay: $0,43700).

**Comment by sccosel** [comment]
@abickerton I assure you it's not you.  The documentation is not wrong.  Try to understand the explanation here: https://github.com/openmainframeproject/cobol-programming-course/issues/44.  Then let us know if you still have more questions!

**Comment by paulnewt** [comment]
team is working on creating a md, mark down, doc in github for us to include all the excellent improvement suggestions .... we are waiting for md to be complete before we start hacking away at the doc - again - thanks for all the observations / contributions for improvement
