### ISSUE TITLE
Error of Authorizaton failed on STEP 20, of Lab 1

### ISSUE THREAD

**Issue by thyarles** [openmainframeproject/cobol-programming-course#43]
I'm getting the following error on this step of Lab1:

**20. Expand Z99998.CBL to view COBOL source members, then select member HELLO to see a simple COBOL ‘Hello World!’ program as shown in Figure 21.** 
_Retrieving response from zowe.List Error: z/OSMF REST API Error: Rest API failure with HTTP(S) status 500 category: 4 rc: 8 reason: 0 message: LMOPEN error details: - ISRZ002 Authorization failed - You may not use this protected data set. Open 913 abend._

Until there everything works. I'm using this address https://192.86.32.250:10443 with my user id and password received on e-mail.

Someone else is getting the same error?

**Comment by MrGmaw** [comment]
> 
> 
> I'm getting the following error on this step of Lab1:
> 
> **20. Expand Z99998.CBL to view COBOL source members, then select member HELLO to see a simple COBOL ‘Hello World!’ program as shown in Figure 21.**
> _Retrieving response from zowe.List Error: z/OSMF REST API Error: Rest API failure with HTTP(S) status 500 category: 4 rc: 8 reason: 0 message: LMOPEN error details: - ISRZ002 Authorization failed - You may not use this protected data set. Open 913 abend._
> 
> Until there everything works. I'm using this address https://192.86.32.250:10443 with my user id and password received on e-mail.
> 
> Someone else is getting the same error?

I think you must creat a new connection with your ID and password, the ones sent by mail. You must expand your user id.cbl (Z800XX.CBL)

**Comment by mthomp9838** [comment]
I'm getting the same error at the same point and the expanded Z99998.CBL shows no data.
I've followed Paul Newton's instructions to delete the "LearnCOBOL.yaml" credentials, restart VSCode,  and re-do the connection several times, but still can't get past this point.

**Comment by mthomp9838** [comment]
Here's what my LearnCOBOL.yaml connection file looks like (with *** instead of my actual ID and password):

[LearnCOBOL.yaml.txt](https://github.com/openmainframeproject/cobol-programming-course/files/4497679/LearnCOBOL.yaml.txt)

**Comment by mthomp9838** [comment]
Here's what my LearnCOBOL.yaml connection file looks like (but with asterisks instead of my actual ID and password):
[LearnCOBOL.yaml.txt](https://github.com/openmainframeproject/cobol-programming-course/files/4497689/LearnCOBOL.yaml.txt)

**Comment by thyarles** [comment]
> > I'm getting the following error on this step of Lab1:
> > **20. Expand Z99998.CBL to view COBOL source members, then select member HELLO to see a simple COBOL ‘Hello World!’ program as shown in Figure 21.**
> > _Retrieving response from zowe.List Error: z/OSMF REST API Error: Rest API failure with HTTP(S) status 500 category: 4 rc: 8 reason: 0 message: LMOPEN error details: - ISRZ002 Authorization failed - You may not use this protected data set. Open 913 abend._
> > Until there everything works. I'm using this address https://192.86.32.250:10443 with my user id and password received on e-mail.
> > Someone else is getting the same error?
> 
> I think you must creat a new connection with your ID and password, the ones sent by mail. You must expand your user id.cbl (Z800XX.CBL)

Hi @MrGmaw , **Solved!**, thanks!

It is the problem... I was trying to use the ID of the step "Z99998", but I need to use my ID. My bad. Maybe write again that user must change this code by their code in this step will be useful.

**Comment by mthomp9838** [comment]
Well, I did use my correct Mainframe ID and Password per the email from zskills@us.ibm.com and still am getting the error.

**Comment by MrGmaw** [comment]
> 
> 
> Well, I did use my correct Mainframe ID and Password per the email from [zskills@us.ibm.com](mailto:zskills@us.ibm.com) and still am getting the error.

Can you see under DATA SETS -> LearnCOBOL  your connection user as: Z800XX.CBL ?

**Comment by MrGmaw** [comment]
Join the slack course group here https://github.com/openmainframeproject/cobol-programming-course 
under DISCUTION topic

**Comment by sccosel** [comment]
@mthomp9838 On this system, you cannot view another user’s datasets (files). Use you own id, Z80xxx, as the “filter” or search criteria. The Z99998.xxxxx datasets do not belong to you, and cannot be browsed, per the security enacted on this system.

**Comment by mthomp9838** [comment]
Thank you!  How obvious in retrospect.  Works fine with my own ID.

**Comment by thyarles** [comment]
Solved.
