### ISSUE TITLE
 LAB2 issues? After 2 compiling, successful display $437.00

### ISSUE THREAD

**Issue by Dlthomass** [openmainframeproject/cobol-programming-course#44]
These steps, may need to be aware of:
1. update the data set if you reopen the VS code, need to set new filter to download your own
2. follow the instructions to idetify the lines which show the wrong clause used for Numeric figure
3. back to CBL, amend   gross pay variable clause  x(5) to $$$$$.99 and save, resubmit job.

**Comment by sccosel** [comment]
@Dlthomass - The solution your provided in your Step #3 above may have worked correctly in this modern Cobol compiler, but it is not considered good style and may not work in older Cobol compilers.  You see, you cannot use a "DISPLAY" type definition within a COMPUTE statement.  A character, such as "$" or ".", makes your GROSS-PAY variable a "DISPLAY" type variable.  The proper way to use "DISPLAY" type variables is to MOVE a value to it, after calculating it using a numeric defined variable.  So, your GROSS-PAY could be defined as PIC 9(5)V99 and then moved to a new variable, GROSS-PAY-DISPLAY PIC $(4)9.99. The "V" represents an implied decimal point.  The new definition means, print a "$" immediately to the left of the first significant number (greater than zero), within a 4-byte field.  The "9.99", means print all digits, when the value contained in this variable is less than 10.00.  This is a technique to ensure zero is printed as "0.00" or in this case, "$0.00".  In your example, zero would print as "$.00".  Perhaps that is what you would prefer.

**Comment by Dlthomass** [comment]
@sccosel thank u
