### ISSUE TITLE
9.2.3 Conditional Names example won't compile

### ISSUE THREAD

**Issue by OldGuy86** [openmainframeproject/cobol-programming-course#50]
9.2.3. in the COBOL Programming with VSCode.pdf document doesn’t correctly demonstrate the relationship between conditional variables and their related condition-names.

Example 1 shows a conditional variable, USA-STATE, with one related condition-name, STATE, which is true whenever USA-STATE contains the value ‘TX’:

   01 USA-STATE PIC X(2) VALUE SPACES. 
        88 STATE VALUE 'TX'. 

The text implies, and the example demonstrates, that the condition-name can be modified:

   MOVE 'AZ' TO STATE. 

That line won’t compile, since 88-levels themselves aren’t modifiable. Instead, the value in USA-STATE must be modified to change the state (TRUE or FALSE) of the condition name. The example should read:

    MOVE ‘AZ’ to USA-STATE.

and 

    MOVE ‘TX’ to USA-STATE.

The text also needs to be modified accordingly.

**Comment by paulnewt** [comment]
thank for the very important oversight - correction will be high priority correction in the documentation ... thanks for the contribution

**Comment by OldGuy86** [comment]
Section 9.4.3 needs some work too. If the example is using a relational condition, it should read:
PERFORM SAY-SOMETHING-DIFFERENT UNTIL FACIAL-EXP = 'HAPPY'.
If it was intended to use a condition-name as suggested in the text, is should be along the lines of:
PERFORM SAY-SOMETHING-DIFFERENT UNTIL HAPPY.
It's hard to say exactly without seeing the definition of the condition-name.

**Comment by OldGuy86** [comment]
I don't see a way to get the example in section 9.4.4 Search statements to compile either. It might help if you showed the definition of the table and condition-names.

**Comment by MrGmaw** [comment]
> 
> 
> 9.2.3. in the COBOL Programming with VSCode.pdf document doesn’t correctly demonstrate the relationship between conditional variables and their related condition-names.
> 
> Example 1 shows a conditional variable, USA-STATE, with one related condition-name, STATE, which is true whenever USA-STATE contains the value ‘TX’:
> 
> 01 USA-STATE PIC X(2) VALUE SPACES.
> 88 STATE VALUE 'TX'.
> 
> The text implies, and the example demonstrates, that the condition-name can be modified:
> 
> MOVE 'AZ' TO STATE.
> 
> That line won’t compile, since 88-levels themselves aren’t modifiable. Instead, the value in USA-STATE must be modified to change the state (TRUE or FALSE) of the condition name. The example should read:
> 
> ```
> MOVE ‘AZ’ to USA-STATE.
> ```
> 
> and
> 
> ```
> MOVE ‘TX’ to USA-STATE.
> ```
> 
> The text also needs to be modified accordingly.
WORKING-STORAGE SECTION.
*     Switch to control the Enf Of File flag 88 MARGIN B
           88 EOF-ACCT-REC               VALUE HIGH-VALUES .

PROCEDURE DIVISION.
...
READ-NEXT-RECORD.
           PERFORM READ-RECORD
           **PERFORM UNTIL EOF-ACCT-REC**
            PERFORM WRITE-RECORD
            PERFORM READ-RECORD
           END-PERFORM
...
READ-RECORD.
      * Read sequentialy file records
           READ ACCT-REC AT END SET EOF-ACCT-REC TO TRUE
           END-READ
           .
