### ISSUE TITLE
Update Needed to Return Email containing Credentials

### ISSUE THREAD

**Issue by sccosel** [openmainframeproject/cobol-programming-course#53]
After someone requests their credentials: [here](https://www-01.ibm.com/events/wwe/ast/mtm/cobolvscode.nsf/enrollall?openform)

The return email should direct them: [here](https://github.com/openmainframeproject/cobol-programming-course/)

and instruct them to (or suggest they) download the [PDF Version](https://github.com/openmainframeproject/cobol-programming-course/releases/download/2.0.0/COBOL-Programming-Course-1-Getting-Started.pdf) of the class instruction manual (materials), [COBOL Programming with VSCode](https://github.com/openmainframeproject/cobol-programming-course/blob/master/COBOL%20Programming%20Course%20%231%20-%20Getting%20Started/COBOL%20Programming%20Course%20%231%20-%20Getting%20Started.md).  The free [Acrobat Reader](https://get.adobe.com/reader/) can be downloaded if needed to view the .pdf file.  Note: The .md version is the official, up-to-the-minute updated version of the class materials.  The .pdf version is generated from the .md version on a regular basis, so it may not reflect the most up-to-date changes.  A version number/date to be published within the .pdf document has been proposed by project participants, so currently, it is not easily determinable if the .pdf version includes the absolute most recent updates and corrections made to the .md version. 

Also a reminder to please follow the instructions, STEP by STEP and to always substitute their **Z8xxxx** id, issued above, in place of the _example id_, **Z99998**, wherever it is mentioned in the class instruction manual.

Also, the return email should include the following IP addresses needed for the course, and explain that the class instruction manual will explain when they will be needed:
IP address for VSCode extension: https://192.86.32.250:10443 <== This link is not meant to be clicked!
IP address for TN3270: 192.86.32.250 Port 623
IP address for IDz: 192.86.32.250 Port 4035

Additionally, the slack channel should be mentioned, for questions and discussion: [here](https://openmainframeproject.slack.com/)

## FAQ:
1. "I'm having a very hard time connecting with the mainframe.  What should I do?"

Post your .yaml file in the Slack Channel Forum, but don't post any passwords. .yaml location: C:\Users\<your Win Id>\.zowe\profiles\zosmf\LearnCOBOL.yaml  Hopefully, someone can help you spot the problem.

Try shutting down VSCode and relaunch.

If that doesn't work, shut down VSCode, try deleting the .yaml file, relauch and create a New Connection again.  Eventually, it will work.  Very buggy.

Also, you could have timed out, if you've connected before.  Need to re-Authenticate.  Shut down VSCode and relaunch.

If clicking on the "Refresh All" icon to the right of "DATA SETS" or the "Search Data Sets..." icon to the right of "LearnCOBOL" (also in the "DATA SETS" area) and nothing happens, try clicking on "LearnCOBOL" itself in the "JOBS" area.  This version (v0.4.9) of Z Open Editor is buggy.  If you receive, "Check Credentials" (Blue pop-up box appears), **click it**, re-authenticate at top.  Ignore any "rse" error messages. Continue anyway.

Other things to try, watch this video.  The presenter actually walks through the process, although I think it was with an older, more stable version of IBM Z Open Editor.  [Get hands on! Run a COBOL program](https://developer.ibm.com/technologies/cobol/videos/get-hands-on-run-a-cobol-program) - Webinar - Originally broadcast: 2020-04-24 - 40 minutes

2. "How do I make numbers print properly?"
  * [Explanation of Cobol Display Variables](https://github.com/openmainframeproject/cobol-programming-course/issues/44).

3. "I've completed the course, now what?"
  * [Self-Study](https://github.com/openmainframeproject/cobol-programming-course/issues/46)
  * [COBOL Challenge: Covid-19 Reports - Real World Challenge #1](https://medium.com/@jessielaine.punongbayan/cobol-challenge-covid-19-reports-ee03a946bd23) by Jessielaine Punongbayan
  * [Zowe-COBOL Challenge: The Unemployment Claims - Real World Challenge #2](https://medium.com/@jessielaine.punongbayan/zowe-cobol-challenge-the-unemployment-claims-2e35a42eabaa?source=friends_link&sk=81163043d7dea63710aedc802172dfca) by Jessielaine Punongbayan
* [COBOL Programming Course #2 - Advanced Topics - COBOL Challenges](https://github.com/openmainframeproject/cobol-programming-course/blob/master/COBOL%20Programming%20Course%20%232%20-%20Advanced%20Topics/COBOL%20Programming%20Course%20%232%20-%20Advanced%20Topics.md#cobol-challenge---debugging)

## IBM Resources:

**COBOL Fridays:**
1. [A Beginner's Practical Approach to COBOL](https://developer.ibm.com/technologies/cobol/videos/cobol-programming-with-vscode-course-launch-webinar) - Webinar presented by Prof. Tak Auyeung of American River College - Originally broadcast: 2020-04-17 - 1 hour (or on [YouTube](https://youtu.be/ycHXzbAmY94))
1. [Get hands on! Run a COBOL program](https://developer.ibm.com/technologies/cobol/videos/get-hands-on-run-a-cobol-program) - Webinar presented by Makenzie Manna - Originally broadcast: 2020-04-24 - 40 minutes (or on [YouTube](https://youtu.be/0HiJu9JdZ08))
1. [Let's Talk Syntax - Cobol Syntax, Structure and File Handling Unique to Cobol](https://developer.ibm.com/technologies/cobol/videos/lets-talk-syntax-cobol-structure-and-file-handling) - Webinar presented by Tom Ross, Captain COBOL - Originally broadcast: 2020-05-01 - 1 hour (or on [YouTube](https://youtu.be/BdfrbDhsGZg))
1. [Let's Talk Syntax - Data Types and Handling Variables](https://developer.ibm.com/components/ibmz/videos/lets-talk-syntax-data-types-and-handling-variables) - Webinar presented by Dr. David Woolbright of Columbus State University - Originally broadcast: 2020-05-08 - 1 hour (or on [YouTube](https://www.youtube.com/watch?v=-uzd8g_wVY4))
1. [Let's Talk Syntax - Branching Logic](https://developer.ibm.com/technologies/cobol/videos/cobol-fridays-lets-talk-syntax-branching-logic) - Webinar presented by Will Yates - Originally broadcast: 2020-05-15 - 1 hour (or on [YouTube](https://youtu.be/5hQSU--j39U))
1. [Let's Talk Syntax - Intrinsic Functions](https://www.crowdcast.io/e/cobol-intrinsic-functions) - Webinar presented by Dr. David Woolbright of Columbus State University - Originally broadcast: 2020-05-22 - 1 hour (or on [YouTube](https://youtu.be/U99aARmmyPQ))
1. [Ready, Set, Code - Write your first COBOL Program (hands on)!](https://developer.ibm.com/technologies/cobol/videos/cobol-fridays-ready-set-code-write-your-first-cobol-program) - Webinar presented by Jeff Bisti - Originally broadcast: 2020-05-29 - 1 hour (or on [YouTube](https://www.youtube.com/watch?v=oV6U8nR9bYw))
1. [What’s next? Solve the COBOL puzzle](https://developer.ibm.com/videos/cobol-fridays-whats-next-solve-the-cobol-puzzle/) - Webinar presented by Scott Cosel from UC Irvine - Originally broadcast: 2020-06-05 - 1 hour (or on [YouTube](https://youtu.be/R-cIyKlsa78))
1. [COBOL Treasures - What's new in COBOL for z/OS since V4.2](https://www.youtube.com/watch?v=IlzmOwcLstw) - Webinar presented by Tom Ross, Captain COBOL, promoted to Colonel COBOL - Originally broadcast: 2020-06-19 - 54 minutes (or on [YouTube](https://youtu.be/IlzmOwcLstw))

* Links to the entire series of recorded sessions (above) will also be posted on these sites, when available: [IBM Developer - COBOL Videos](https://developer.ibm.com/technologies/cobol/videos/) -OR- [COBOL Fridays webcast series](https://developer.ibm.com/series/cobol-fridays-webinar-videos/) -OR- [EventBrite - All Past Events - Past Events Tab](https://www.eventbrite.com/o/ibm-z-30113857682) -OR- [YouTube - COBOL Fridays](https://www.youtube.com/watch?v=0HiJu9JdZ08&list=PLzpeuWUENMK2-pANOj6C1aXyd8puKqhT2)

**Next Cobol webinar: Friday, July 3, 2020, 12:00-1:00 p.m. Eastern Time:**
* COBOL Fridays: TBA - Registration: TBA - Recorded session: TBA after event has concluded - Link to recorded session will be posted on this site, when available: [IBM Developer - COBOL Videos](https://developer.ibm.com/technologies/cobol/videos/) -OR- [COBOL Fridays webcast series](https://developer.ibm.com/series/cobol-fridays-webinar-videos/) -OR- [EventBrite - All Past Events - Past Events Tab](https://www.eventbrite.com/o/ibm-z-30113857682) -OR- [YouTube - COBOL Fridays](https://www.youtube.com/watch?v=0HiJu9JdZ08&list=PLzpeuWUENMK2-pANOj6C1aXyd8puKqhT2)

**Other Resources:**

* [Want to become a Tech Entrepreneur? Here’s how I did it & you can too](https://ibm.webex.com/recordingservice/sites/ibm/recording/play/16546b7dc0274b90a313f2fbe1f86706) - Webinar - Originally broadcast: 2020-04-23 - 1 hour

* [IBM Developer - COBOL](https://developer.ibm.com/technologies/cobol/)
* [IBM Z and LinuxONE Community](https://www.ibm.com/community/z/)
* [Master the Mainframe - Get hands-on Experience Across a Variety of Technologies](https://www.ibm.com/it-infrastructure/z/education/master-the-mainframe)
* [Open Mainframe Project Website - The Linux Foundation Projects](https://www.openmainframeproject.org/)
* [IBM and Open Mainframe Project Mobilize to Connect States with COBOL Skills](https://newsroom.ibm.com/2020-04-09-IBM-and-Open-Mainframe-Project-Mobilize-to-Connect-States-with-COBOL-Skills)

Additional Course Resources:
* YouTube Video: [So you want to learn COBOL?](https://youtu.be/77o14aHUuSo)
* [An Introduction to the Zowe Virtual Desktop](https://medium.com/zowe/an-introduction-to-the-zowe-virtual-desktop-6e0140644875)

* [IBM Enterprise COBOL for z/OS Documentation Library](https://www.ibm.com/support/pages/enterprise-cobol-zos-documentation-library) - Full Reference Library of COBOL Manuals
* [IBM Enterprise COBOL for z/OS,  Language Reference v6.3](http://publibfp.boulder.ibm.com/epubs/pdf/igy6lr30.pdf)
* [IBM Language Environment Programming Reference v2r4](https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zosV2R4SA380683/$file/ceea300_v2r4.pdf) - Common subroutines callable from all IBM supported programming languages.
* [IBM Enterprise COBOL for z/OS, Messages and Codes v6.3](http://publibfp.boulder.ibm.com/epubs/pdf/c2746481.pdf)
* [IBM Setting property groups | IBM Z® Open Editor](https://ibm.github.io/zopeneditor-about/Docs/setting_propertygroup.html#mvs-property-groups-using-the-zowe-cli)
* [Installing Zowe CLI from an online registry](https://docs.zowe.org/v1-1-x/user-guide/cli-installcli.html#installing-zowe-cli-from-a-local-package)
* [Installing Zowe CLI from source](https://github.com/zowe/zowe-cli#install-zowe-cli-from-source)

* [IBM z/OS MVS JCL Reference v2r4](https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R4sa231385/$file/ieab600_v2r4.pdf)
* [IBM z/OS Communications Server: IP User's Guide and Commands v2r4](https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R4sc273662/$file/halu001_v2r4.pdf) - FTP Reference Manual
* [IBM z/OS TSO/E REXX Reference v2r4](https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R4sa320972/$file/ikja300_v2r4.pdf)
* [IBM DFSORT: ICETOOL Mini-User Guide](https://www.ibm.com/support/pages/sites/default/files/inline-files/$FILE/sorttool.pdf) - October, 2010 by Frank L. Yaeger
* [DFSORT′s Year 2000 Features (The New Generation)](https://www.ibm.com/support/pages/sites/default/files/inline-files/$FILE/sort2000.pdf) - October, 1998 by Frank L. Yaeger
* [IBM DFSORT Application Programming Guide v2r4](https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R4sc236878/$file/icea100_v2r4.pdf) - Full Manual
Note: IBM DFSORT's ICETOOL can often replace the need to write COBOL program(s), when needing to (optionally) sort and tranform data contained in one or more input files to produce an output file.  All user guides written by Frank L. Yaeger on this subject are excellent.  Access the entire collection, [here](https://www.ibm.com/support/pages/dfsortmvs-downloads).

Restoring a Fresh Copy of Lab Data (or Cobol) Files:
* Download data file from Labs folder from: [here](https://github.com/openmainframeproject/cobol-programming-course/tree/master/Labs/data) then go to the command line and execute zowe zos-files upload file-to-data-set "data" "Z8XXXX.DATA" -b

More education from IBM:
* [z/OS Introduction and Workshop for IT Professionals](http://ibm.biz/zOSclass)

History:
* [Timeline and brief description of IBM Operating Systems. By Dave Morton, marspyrs. Dated: February, 2018](https://webfiles.uci.edu/scosel/_$OSTL37.5.pdf)

Internet resources:
* [Beginner’s Guide: COBOL Made Easy](https://medium.com/modern-mainframe/beginners-guide-cobol-made-easy-introduction-ecf2f611ac76) by Jessielaine Punongbayan
* [Awesome Mainframes - Useful Links for z/OS and the Hercules Emulator](https://github.com/FuzzyMainframes/Awesome-Mainframes/blob/master/README.md)
* [Dr. David Woolbright's (COBOL Fridays: Presenter) Website](https://punctiliousprogrammer.com/)
* [DB2 SQL Cookbook](http://db2-sql-cookbook.org/pdf/Db2_SQL_Cookbook.pdf) based upon the original work of Graeme Birchall: 
* [DB2 SQL Cookbook - Original Archived PDF](https://web.archive.org/web/20130115084328/http://mysite.verizon.net/Graeme_Birchall/cookbook/DB2V97CK.PDF)
* [Fake Your Way Through Minis and Mainframes - Including MVS (predecessor to z/OS)](http://www.snee.com/bob/opsys.html)

Employment Opportunity - Cobol Programmers Needed Now!
* [State of New Jersey](https://forms.business.nj.gov/tech/)

I think what is happening, is people have found out about this course via all sorts of different methods, and there is no one place that has all of the above needed information.  The return email would be a good place (although not the only place) where such information should/could be found.

Really enjoying the course and the Cobol Community that you have formed!
Keep up the good work!

Thank you,
ScottC

**Comment by paulnewt** [comment]
Excellent suggestion.  The confirmation will be changed after a mark down document replaces the pdf.  A mark down document is the priority to implement many of the recommendations for improvement.

**Comment by jellypuno** [comment]
I think this issue should be part of the [Cobol Course](https://github.com/openmainframeproject/cobol-programming-course/blob/master/COBOL%20Programming%20with%20VSCode.md). A new chapter named TL;DR 😄

**Comment by cobol10** [comment]
@jellypuno 
I completely agree!

**Comment by sccosel** [comment]
@jellypuno @cobol10 Is that supposed to be funny?  "TL;DR" = "Too Long; Didn't Read" - You 2 didn't read it because it was too long? Huh? Seriously?  Do you know everything there is to know about Cobol and z/OS?  @paulnewt - Isn't insulting another contributor's work against community standards?

**Comment by cobol10** [comment]
@sccosel I only suggest including as a separate section in "COBOL Programming with VSCode"! I do not propose to name a new section "TL;DR"! You understood me wrong. Thank you so much for this stuff!

**Comment by Dlthomass** [comment]
@sccosel is a warm hearted contributor, we all respect you with your great work. Dont be upset, have a nice weekend.

**Comment by jellypuno** [comment]
@sccosel hold on... tl;dr is just a slang that says here's a summary of what you need to do. which re-directs them to the cobol learning itself. I thought everybody knows this terminology and I didn't mean it to come as an insult. I would never do that especially for a great work such as this. All I wanted to say is that what you have done in this issue if very useful and I found it helpful and I think adding it to the course would be a great help to everyone as well.

**Comment by BaileyH** [comment]
I have been looking for this information for a couple of weeks! So happy to have a concise getting started guide!

**Comment by steven-piot** [comment]
perfect, thank you Scott!

**Comment by MikeBauerCA** [comment]
Closing as no further action is required here. This issue can continue to serve as a getting started point. We have also updated our READMEs with some of this content.

**Comment by AbidAbed** [comment]
💯

**Comment by AbidAbed** [comment]
Fake Your Way Through Minis and Mainframes
