### ISSUE TITLE
Lab 1: Error creating profile and accessing data sets

### ISSUE THREAD

**Issue by MLo8** [openmainframeproject/cobol-programming-course#54]
Hello, I am reading the guide and got to Lab 1.  I registered for and received my mainframe ID and password (yay).  I followed the steps up through the "accept" selection... at that point I get the following error:

"Expect Error: Could not locate the profile type configuration for "rse" within the input configuration list passed..."

It did create the "Favorites" folders and I was able to get through to the filter step but then get this error:  "Invalid Credentials. Please ensure the username and password for LearnCOBOL  are valid or this may lead to a lock-out."

Could you please help me?

**Comment by sccosel** [comment]
(Suggestion) Follow this!  https://github.com/openmainframeproject/cobol-programming-course/issues/53

**Comment by MLo8** [comment]
Thank you sccosel.  I followed all of those steps and received the email with my unique ID and PW.  I have the documentation which I'm following and i just watched the webinar... however I still get that odd error.  I even found your suggestion to another user on #28 regarding editing the .yaml file.  I looked at that and found that I had originally mistyped my password (oops)... I edited it, but didn't work... then deleted it and tried again (several times) but still same error.

**Comment by MLo8** [comment]
@sccosel On a related note, I don't have a slack account... when I went to the link it lists several email domains that can create an account but I'm not on any of those.  I read that you can be invited to the workspace... do you happen to know how I can get onto Slack for this group?  Sorry for my ignorance on these items.

**Comment by sccosel** [comment]
@MLo8 I believe you must use the email id that you used to sign up to get your credentials.  No other email id will work.  And you went here: https://openmainframeproject.slack.com/ ?

**Comment by MLo8** [comment]
@sccosel Yes, that is the PW I received in the registration email (I originally typed in ACOBOL by mistake)... Slack doesn't recognize my email... and it is definitely the one I used in registration because I received the registration email... I'm wondering if I should try to re-register (?).

**Comment by sccosel** [comment]
@MLo8 Hopefully, one of the administrators, can help you.  Paul Newton has been very helpful. paulnewt@us.ibm.com

**Comment by paulnewt** [comment]
if struggling with connection credentials .... workstation home folder > .zowe > profiles > zosmf > find your connection_name.yaml .... delete it .... create connection name again reading instructions very carefully.... and be sure to connect first using Zowe Extension Data Sets tab  ... be sure to restart VSCode after deleting connection_name.yaml

**Comment by jackson-024** [comment]
Hello,so i have followed all steps but when it comes to the point of getting the data sets i get this error "Retrieving response from zowe.List Error: z/OSMF REST API Error: http(s) request error event called Error: getaddrinfo ENOTFOUND 192.86.32.250.10443"
could someone please help?

**Comment by sccosel** [comment]
Try 192.86.32.250:10443

**Comment by MLo8** [comment]
@paulnewt thanks, I did try this numerous times... I even uninstalled and reinstalled Java and VSCode & extensions per instructions, in case that had something to do with it... but still the same... "Expect Error: Could not locate the profile type configuration for "rse" within the input configuration list passed..." 

P.S. can I be invited to the Slack workspace?  Per Slack, I cannot create an account to log in unless someone on the team sends me an invite.

**Comment by MLo8** [comment]
Well... I finally got access to the slack workspace, reset my ID/PW and now it works... I believe that because I originally mistyped the PW creating the profile and tried a few times I got locked out... whew!  Thank you @paulnewt and @sccosel for your help... now I can actually get started :)
