### ISSUE TITLE
IBM Java 8

### ISSUE THREAD

**Issue by gowide00** [openmainframeproject/cobol-programming-course#57]
I'm doing the VS Code set up and IBM Java 8 is a prerequisite for IBM Z Open Editor.  I'm using Windows 10 but I'm not sure which version of IBM Java 8 to use.  Should I install IBM Eclipse or should I use the Linux install.  I enabled Linux on my laptop.

I'm a little confused.  I'm not sure where to configure Java either.

**Comment by sccosel** [comment]
(Suggestion) Follow this, STEP by STEP: https://github.com/openmainframeproject/cobol-programming-course/issues/53

**Comment by cobol10** [comment]
@gowide00 Do not worry. I advise you to work in Windows 10.

**Comment by gowide00** [comment]
> (Suggestion) Follow this, STEP by STEP: #53

Thanks this solved my initial solution.  The return email I received with a Mainframe ID and password had a link to Open Mainframe Project Slack but my email wasn't registered with Slack.  I have another question but I'm unable to post on Slack because I can't get in.

**Comment by cobol10** [comment]
@gowide00 
I don’t remember how I got access to Slack, but try here:
https://slack.com/signin
