### ISSUE TITLE
Error in 15.3.6 Saving your work 

### ISSUE THREAD

**Issue by OldGuy86** [openmainframeproject/cobol-programming-course#61]
Section 15.3.6 in COBOL Programming with VSCode.pdf states:

   ➢ Typing =X on the command line exits ISPF edit back to the Primary Option Menu. 
       o Note that you will be prompted to save or cancel changes to the file. 

That is incorrect. Typing =X on the command line terminates ISPF, returning you to the TSO READY prompt. Changes are automatically saved.

**Comment by MikeBauerCA** [comment]
The course no longer includes ISPF
