### ISSUE TITLE
Cross-references are broken

### ISSUE THREAD

**Issue by MikeBauerCA** [openmainframeproject/cobol-programming-course#62]
Cross-references in https://github.com/openmainframeproject/cobol-programming-course/blob/master/COBOL%20Programming%20with%20VSCode.md are broken.

For example, clicking on "Chapter 1. Why COBOL?" in the document does nothing.

**Comment by sccosel** [comment]
Hi All, @MikeBauerCA is working on correcting this.  If anyone else is also interested in changing the chapter numbering to use automagic numbering (rather than hardcoded), please coordinate with Mike so work is not duplicated.  Contact Mike on Slack, or here.  Thanks!

**Comment by MikeBauerCA** [comment]
Closing. Resolved by #77
