### ISSUE TITLE
Wrong Chapter Referenced for Installing VS Code and Extensions

### ISSUE THREAD

**Issue by brkline** [openmainframeproject/cobol-programming-course#75]
In Chapter 2, section 2.1.3 of COBOL Programming with VSCode.md, it says:

> To see a more detailed instruction on installing this extension, visit Chapter 5 "Install VSCode and Extensions".

However, Chapter 5 is Data Division according to the Table of Contents.  Chapter 3 is titled Installation of VSCode and extensions according to the Table of Contents.

**Comment by binary-sequence** [comment]
Resolved in #77
