### ISSUE TITLE
How do you sign up for the IBM Coursera Cobol Course?

### ISSUE THREAD

**Issue by sccosel** [openmainframeproject/cobol-programming-course#8]
I am unable to locate it in the Coursera website.

Thank you,
ScottC

**Comment by navarretedaniel** [comment]
Hi Scott. I'm not affiliated with this project but I saw that IBM's April 9 [announcement](https://newsroom.ibm.com/2020-04-09-IBM-and-Open-Mainframe-Project-Mobilize-to-Connect-States-with-COBOL-Skills) states that self-service video courses will be available on Coursera (and other platforms) **next month**.

> Open Source COBOL Training – a brand new open source course designed to teach COBOL to beginners and refresh experienced professionals. IBM worked with clients and an institute of higher education to develop an in-depth COBOL Programming with VSCode course that will be available next week on the public domain at no charge to anyone.  This curriculum will be made into a self-service video course with hands-on labs and tutorials available via Coursera and other learning platforms next month. The course will be available on IBM’s own training platform free of charge.

**Comment by mconfoy** [comment]
IBM said on the previous issue that the course will be available next week. Not sure if it will be the best way to learn it depending on your background I imagine. COBOL different than every other language.

**Comment by Sudharsana-Srinivasan** [comment]
The course content will be available here from April 14th. The video course, which will be available on Coursera and other platforms, will launch in late May. As @navarretedaniel pointed out in his comment above.

**Comment by sccosel** [comment]
Thank you, @Sudharsana-Srinivasan, for putting the course together!

**Comment by ftpo** [comment]
Experienced Cobol developer (1985-1995) on HP3000 & databases, needs refresh but might be quickly ok, how to join?
French native, I'm in Leeds, UK, for the moment.

**Comment by bhowe** [comment]
There are a few paid courses out there that are pretty reasonable if you want to get a head start.

**Comment by Sudharsana-Srinivasan** [comment]
The course content is now available here

**Comment by rsac56** [comment]
I learned Cobol way back in 1989-90. I never actually worked in that area, but I did work in FORTRAN and Clipper. I’m not sure at what level to begin; experienced or new since it’s been so long.

**Comment by Eliana88** [comment]
Hi. I'm a Cobol Devoloper from Argentina. Good initiative.

**Comment by BilltheK** [comment]
Sudharsana, where do I sign up?

**Comment by kas1830** [comment]
> Sudharsana, where do I sign up?

https://www-01.ibm.com/events/wwe/ast/mtm/cobolvscode.nsf/enrollall?openform

**Comment by kas1830** [comment]
https://www.coursera.org/learn/cobol-programming-vscode?
