### ISSUE TITLE
Future COBOL Friday Topic Requests

### ISSUE THREAD

**Issue by sccosel** [openmainframeproject/cobol-programming-course#82]
I’m interested in starting a list somewhere, which would allow community members to request topics of interest to be the subject  of future COBOL Friday Webinars.  And, through the use of some kind of polling mechanism, allow the entire community to vote for the topics (ranking them in order of preference or just allow one vote per week, etc.) that they are most interested in. Where would be the best place to do this?  Looking for feedback from others regarding the interest in this subject. Please leave comments below.

Suggested as possible future topics:

1) Real world situations - Loading a spreadsheet full of input data into a mainframe, COBOL readable input file, i.e. properly converting raw input, which would include numbers, negative numbers and text, even introducing literals into the converted file.  Note: I could present this session.

2) Practical uses of DFSORT and/or ICETOOL.

**Comment by MrGmaw** [comment]
Hi Scossel, I think that this could be a good place to do it. By the way, I'd like to learn how to create and handle Db2 database and relations (tables) with COBOL, zowe cli/visual Code.

**Comment by sccosel** [comment]
@MrGmaw Thanks for your comments!  Just a reminder, that these sessions are only 1 hour in length, and are not meant to be complete training courses. There are videos on the Internet, which already cover heavy duty topics.  I think real world scenarios/tips and tricks are well suited to this method of delivery.  Scott

**Comment by binary-sequence** [comment]
Hi @sccosel,

When I need to make a poll, I use https://doodle.com
It also allows to close and reopen the poll.

So, for example the poll can be closed on Friday, stream the session, then edit the poll removing the topic already covered in the session (and add more topics) and reopen the poll again until next Friday.

**Comment by sandeep-sparrow** [comment]
required this topic for better learning

Real-world situations - Loading a spreadsheet full of input data into a mainframe, COBOL readable input file, i.e. properly converting raw input, which would include numbers, negative numbers, and text, even introducing literals into the converted file. Note: I could present this session.

Practical uses of DFSORT and/or ICETOOL.

**Comment by Dlthomass** [comment]
@sccosel which video you talked about? on the Youtube? How to present your new class to us?Via Zoom , Skype?

**Comment by sccosel** [comment]
@Dlthomass - Well, so far, IBM personnel seem to be leading this project and its direction.  They use Webex for their presentations.  I would assume, that if IBM truly wants this "Open Mainframe Project" to be open to the community, then they will invite speakers, some of which do not work directly for IBM, to make presentations.  I have not yet filmed the presentation that I described.  At this point, I would need to prepare it.  The Moshix Channel on YouTube has a lot of how to videos, but they are more geared toward the freely available TK4- which runs a public domain version of MVS 3.8j circa 1985 (z/OS evolved from MVS), with a version of the Cobol compiler dating from the 1960's or early 1970's, and other features which are just too old to learn modern features of current z/OS.  However, learning how to code JCL using that older system is still relevant.  However, once again, some more modern features of JCL are not present, such as IF, ELSE and ENDIF condition checking.  What say you, @paulnewt?

**Comment by paulnewt** [comment]
I agree ... I was just speaking to Sudharsana about turning control over to the community late last week.  Sudharsana, Martin, and I will be discussing it today.   Control also includes reviewer/committer priviledges.

**Comment by Sudharsana-Srinivasan** [comment]
Thank you @sccosel for starting this issue with request for topic suggestions..... I put out a request last week on the Slack Channel. Happy to take in suggestions and coordinate the topics and sessions. If one of you would like to present a topic in this series, please let me know.

**Comment by sccosel** [comment]
Ideas for future Cobol Fridays, originally posted in the Slack Channel, 5/3/2020:
Hey @Paul Newton, looking forward to talking directly with you and @Sudharsana Srinivasan next week. I’d be most interested in presenting intermediate or advanced (combined) topics in a single session involving JCL, Cobol, DFSORT/ICETOOL, GDGs (concepts and usage) and/or uploading an Excel Spreadsheet of values  (including negative numbers) into a dataset directly readable by a subsequent COBOL program. That’s enough for one session!  Perhaps called JCL Tips and Tricks #1,  Another session on sending a job to run on another MVS system, passing a file containing records longer than 80 bytes. This exercises XMIT and RECEIVE commands.  Also retrieving and uploading software obtained from cbttape.org, using BATCHTSO, maybe even running quick and dirty BATCHSQL.  Also could demonstrate Batch FTP to a remote FTP server (MVS or Windows)!  Also, Windows FTP to MVS host including JES job submission. Let me know your thoughts!

**Comment by MikeBauerCA** [comment]
Closing as the COBOL Friday Series has concluded. We are considering launching COBOL quarterly webinars through our Technical Steering Committee where we will provide course updates and may include guest speakers to talk about technical topics related to the course.
