### ISSUE TITLE
Set Up a R/O Shared Set of Unmodified Class Materials

### ISSUE THREAD

**Issue by sccosel** [openmainframeproject/cobol-programming-course#87]
Could someone copy an unmodified set of Class Materials to a separate High Level Qualifier that all users on the system would have R/O access to, such as 'SYS2.Z80000.CBL', 'SYS2.Z80000.JCL', etc.?  This would serve serveral purposes:

1) Have a clean set of files (already loaded on the mainframe) to restore from, in case an individual user "destroys" their copy.

2) Have a place to put additional utility JCL jobs that are created by Admins in response to questions asked in the (Slack, etc.) forums, such as DEFVSAM, as discussed here: https://openmainframeproject.slack.com/archives/C011NE32Z1T/p1587999987108000?thread_ts=1587936917.072900&cid=C011NE32Z1T 

3) Have access to a set of R/O PDS, SEQ and DATA files for the purpose of practicing copying them, using standard IBM utilities, like IEBGENER, SORTGENR, IEBCOPY, etc.

FYI, if granted sufficient RACF authority, I would be glad to take on this task.

Thank you,
Scott

**Comment by paulnewt** [comment]
Unmodified labs data sets are available to all in a read only state
ZOS.PUBLIC.CBL     
ZOS.PUBLIC.DATA    
ZOS.PUBLIC.JCL     
ZOS.PUBLIC.LOAD    
ZOS.PUBLIC.SEQ.DATA

ZOS.PUBLIC.JCL(DEFVSAM) defines VSAM KSDS and copies DATA file content in the VSAM.KSDS

**Comment by paulnewt** [comment]
I can create a single ZOS.PUBLIC.SHARED.JCL (public read/write) for any to add JCL members

**Comment by sccosel** [comment]
@paulnewt Maybe you would want to keep the public files exactly as they were when originally created and create another PDS, say, ZOS.PUBLIC.ADHOC.JCL which contains added JCL beyond the course materials?  Just a thought!  Thanks!

**Comment by paulnewt** [comment]
Data set allocated with public update access ----

ZOS.PUBLIC.ADHOC.JCL($README)
Member names with brief description                                            
DEFVSAM - DEFINE VSAM KSDS & REPRO DATA consisting of a unique key
