### ISSUE TITLE
Automatically generate PDF using CI

### ISSUE THREAD

**Issue by FranklinChen** [openmainframeproject/cobol-programming-course#93]
Now that there is a PDF file generated from Markdown, perhaps remove the PDF from Git and use CI (e.g. Travis CI) to automatically keep the PDF file up to date and upload it somewhere, e.g. using GitHub Pages for the repo?

**Comment by sccosel** [comment]
I'm confused. Where is the .pdf file that can be downloaded?  The one on the "code" page is not usable and Acrobat Reader reports that it is unrecognized.  Also, the size of the file appears to be too small.

**Comment by FranklinChen** [comment]
I was referring to https://github.com/openmainframeproject/cobol-programming-course/blob/master/COBOL%20Programming%20with%20VSCode.pdf

**Comment by sccosel** [comment]
@FranklinChen That version appears damaged.

**Comment by FranklinChen** [comment]
I have it downloaded and open on my screen right now.

**Comment by sccosel** [comment]
@FranklinChen What size is the file?

**Comment by MrGmaw** [comment]
> I have it downloaded and open on my screen right now.

Downloading it, is the only way to open the pdf file, but it displays nothing when click the link https://github.com/openmainframeproject/cobol-programming-course/blob/master/COBOL%20Programming%20with%20VSCode.pdf

**Comment by FranklinChen** [comment]
@MrGmaw Actually that URL displays the pdf for me fine, on my desktop and laptop computers. Are you using a phone?

The "raw" URL should work anywhere, since it is a link to the actual PDF file, rather than a Web page that includes a generated view of the PDF.

https://github.com/openmainframeproject/cobol-programming-course/raw/master/COBOL%20Programming%20with%20VSCode.pdf

**Comment by FranklinChen** [comment]
@sccosel It's a huge file, 6.1 MB.

**Comment by sccosel** [comment]
@FranklinChen Ok, that worked, when I used "Save As" from the link you posed.

**Comment by MrGmaw** [comment]
> @MrGmaw Actually that URL displays the pdf for me fine, on my desktop and laptop computers. Are you using a phone?
> 
> The "raw" URL should work anywhere, since it is a link to the actual PDF file, rather than a Web page that includes a generated view of the PDF.
> 
> https://github.com/openmainframeproject/cobol-programming-course/raw/master/COBOL%20Programming%20with%20VSCode.pdf

Yes I'm using a phone.There isn't a Raw format option.

**Comment by sccosel** [comment]
https://github.com/openmainframeproject/cobol-programming-course/blob/master/COBOL%20Programming%20with%20VSCode.pdf is the link posted on the main "code" page, i.e. "blob" instead of "raw".

**Comment by FranklinChen** [comment]
Right, that's why I think there should be a GitHub Pages site for this project, with a link to actual PDF, rather than just expecting people to use the code view of the repo.

**Comment by MikeBauerCA** [comment]
@FranklinChen the issue I see with the generated PDF is that it will add merge conflicts. In addition to the suggestion of GitHub pages, what do you think about using GitHub releases to distribute the generated PDF?

**Comment by binary-sequence** [comment]
I think it would be beneficial to have both

- the course document in GitHub pages in Markdown and,
- a GitHub action to generate the PDF from the Markdown of the GitHub page and publish it in the **release** section.

**Comment by FranklinChen** [comment]
Since the Markdown source seems to be evolving constantly, it also seems like a good idea for the generated PDF to prominently display a time stamp of the last corresponding commit that changed the Markdown file, else there will be (already maybe are) a proliferation of unversioned PDF files out there.

**Comment by MikeBauerCA** [comment]
Closing for now. We no longer source the PDF. We publish official releases somewhat infrequently and expect most users to consume those official releases. The markdown content is bleeding edge content that is actively being developed and is subject to more frequent changes. Should we decide to publish official releases more frequently in the future, we will revisit using GitHub actions to automate this process.
